name: CI/CD

on:
  push:
    branches: [main]
    paths-ignore: ['**/README.md']
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    paths-ignore: ['**/README.md']

jobs:
  avoid_reduncy:
    runs-on: ubuntu-18.04
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}


  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          node-version: '14'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build


  publish:
    needs: [build]
    runs-on: ubuntu-18.04
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          node-version: '14'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: LS DEL PROYECTO 📚 <--
        run: ls -l
        working-directory: ./packages/ui
      - name: RUNNING SEMANTIC-RELEASE 🚀
        run: yarn semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}