name: Release

on:
  push:
    branches:
      - main
    paths:
      - 'apps/packages/**'
#ls -l
jobs:
  build:
    name: Build
    # if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Root
        run: ls -l
      - name: Run Test
        working-directory: ./packages/ui
        run: node test.js